# Generated by Django 3.2.4 on 2021-06-22 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('sector', models.CharField(max_length=80)),
                ('marketCap', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.stock')),
            ],
            options={
                'ordering': ['date', 'ticker'],
            },
        ),
    ]
